### ISSUE TITLE
Pending items / working in progress

### ISSUE THREAD

**Issue by aldookware** [aldookware/ensibuuko#5]
##  Work in progress
- [x]  creating a DB index or view to speed up data pull during report generation
- [x]  tests for API and fronted
- [x] CI - will handle with GitHub actions or circle ci - easy to setup 
- [x] The project was written with not enough to critically think through some refactoring is required

**Comment by coreysan** [comment]
@aldo, don't worry about these: 
- Front end tests. 
- CI / GitHub Actions / Circle CI

The minimum for the assignment is that the report loads, and in a timely manner. 

Not sure how to read this: 

>  The project was written with not enough to critically think through some refactoring is required

**Comment by aldookware** [comment]
> @aldo, don't worry about these:
> 
> * Front end tests.
> * CI / GitHub Actions / Circle CI
> 
> The minimum for the assignment is that the report loads, and in a timely manner.
> 
> Not sure how to read this:
> 
> > The project was written with not enough to critically think through some refactoring is required

The project was implemented quickly, not a lot thought was put into the design, I think I can do better

And thank you for the clarity on the issues listed above.
