### ISSUE TITLE
The report is not being loaded

### ISSUE THREAD

**Issue by aldookware** [aldookware/ensibuuko#7]
- I noticed a bug the report is not being loaded.   
the report table is blank. 
![Screenshot 2019-12-19 at 22 14 23](https://user-images.githubusercontent.com/7315250/71202306-fcd8b000-22ac-11ea-821e-ba5eb5fb76b8.png)

**Comment by coreysan** [comment]
Thanks for documenting. This is the heart of the assignment, so I'll wait until this is in place to review.

**Comment by coreysan** [comment]
Here's the error I get from the container: 
![image](https://user-images.githubusercontent.com/959458/71221616-27614380-2282-11ea-9167-6529e2c4df06.png)

This is due to the `/vendor` folder not being built, which is due to `composer install` not being run.

**Comment by aldookware** [comment]
> Here's the error I get from the container:
> ![image](https://user-images.githubusercontent.com/959458/71221616-27614380-2282-11ea-9167-6529e2c4df06.png)
> 
> This is due to the `/vendor` folder not being built, which is due to `composer install` not being run.

setting this up as a new issue as I have raised a PR to fix this issue.
